package models

// this file is generated by gooo ORM. DON'T EDIT this file
import (
	"context"
	"database/sql"

	"github.com/version-1/gooo/examples/starter/schema"
)

type scanner interface {
	Scan(dest ...any) error
}
type queryer interface {
	QueryRowContext(ctx context.Context, query string, dest ...any) *sql.Row
	QueryContext(ctx context.Context, query string, dest ...any) (*sql.Rows, error)
	ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error)
}

type NotFoundError struct{}

func (e NotFoundError) Error() string {
	return "record not found"
}

var ErrNotFound = NotFoundError{}

type PrimaryKeyMissingError struct{}

func (e PrimaryKeyMissingError) Error() string {
	return "primary key is required"
}

var ErrPrimaryKeyMissing = PrimaryKeyMissingError{}

func NewUser() *User {
	return &User{
		Schema: schema.UserSchema,
	}
}

func NewUserWith(obj User) *User {
	m := &User{
		Schema: schema.UserSchema,
	}
	m.Assign(obj)

	return m
}

func NewPost() *Post {
	return &Post{
		Schema: schema.PostSchema,
	}
}

func NewPostWith(obj Post) *Post {
	m := &Post{
		Schema: schema.PostSchema,
	}
	m.Assign(obj)

	return m
}
