openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://localhost:8080/api/v1
    description: Optional server description, e.g. Main (production) server

tags:
  - name: User
    description: Operations related to users
  - name: Post
    description: Operations related to posts

paths:
  /users:
    get:
      tags:
        - User
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                fuga: "hoge"
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - User
      summary: Create a User.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MutateUser'
      responses:
        "201": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      tags:
        - User
      summary: Returns a user.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    patch:
      tags:
        - User
      summary: Returns a user.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MutateUser'
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      tags:
        - User
      summary: Delete a user.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /posts:
    get:
      tags:
        - Post
      summary: Returns a list of posts.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      tags:
        - Post
      summary: Create a Post.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MutatePost'
      responses:
        "201":
          description: A JSON array of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  /posts/{id}:
    get:
      tags:
        - Post
      summary: Returns a post.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    patch:
      tags:
        - Post
      summary: Update a post.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MutatePost'
      responses:
        "200":
          description: A JSON array of posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    delete:
      tags:
        - Post
      summary: Delete a post.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of posts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
          sample: "John Doe"
        obj:
          type: object
          properties:
            hoge:
              type: string
              sample: "hoge"
            fuga:
              type: string
              sample: "fuga"
    MutateUser:
      type: object
      properties:
        username:
          type: string
          sample: "John Doe"
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        title:
          type: string
          sample: "Sample Post Title"
        content:
          type: string
          sample: "This is a sample post content."
    MutatePost:
      type: object
      properties:
        title:
          type: string
          sample: "Sample Post Title"
        content:
          type: string
          sample: "This is a sample post content."

