name: Gooo Pipeline
run-name: ${{ github.actor }} is testing out the app
on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'releases/*'
jobs:
  test-packages:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine3.20
    defaults:
      run:
        shell: sh
    env:
      ENV: test
      DATABASE_URL: postgres://gooo:password@db:5432/gooo_test?sslmode=disable
    services:
      db:
        image: postgres:16.2
        env:
          POSTGRES_USER: gooo
          POSTGRES_PASSWORD: password
          POSTGRES_DB: gooo_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: apk add --update-cache git
      - name: Init Database
        run: go run test/cmd/initdb/main.go
      - name: Go mod tidy
        run: go mod tidy
      - name: Run tests
        run: go test -v ./pkg/...
